package com.example.demo.model;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Date;


public class IGood implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_test..i_good.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_test..i_good.good_name
     *
     * @mbggenerated
     */
    private String goodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_test..i_good.good_left
     *
     * @mbggenerated
     */
    private Integer goodLeft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_test..i_good.good_desc
     *
     * @mbggenerated
     */
    private String goodDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_test..i_good.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_test..i_good.created_time
     *
     * @mbggenerated
     */
    private Timestamp createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_test..i_good.updated_time
     *
     * @mbggenerated
     */
    private Timestamp updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table i_test..i_good
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_test..i_good.id
     *
     * @return the value of i_test..i_good.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_test..i_good.id
     *
     * @param id the value for i_test..i_good.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_test..i_good.good_name
     *
     * @return the value of i_test..i_good.good_name
     *
     * @mbggenerated
     */
    public String getGoodName() {
        return goodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_test..i_good.good_name
     *
     * @param goodName the value for i_test..i_good.good_name
     *
     * @mbggenerated
     */
    public void setGoodName(String goodName) {
        this.goodName = goodName == null ? null : goodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_test..i_good.good_left
     *
     * @return the value of i_test..i_good.good_left
     *
     * @mbggenerated
     */
    public Integer getGoodLeft() {
        return goodLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_test..i_good.good_left
     *
     * @param goodLeft the value for i_test..i_good.good_left
     *
     * @mbggenerated
     */
    public void setGoodLeft(Integer goodLeft) {
        this.goodLeft = goodLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_test..i_good.good_desc
     *
     * @return the value of i_test..i_good.good_desc
     *
     * @mbggenerated
     */
    public String getGoodDesc() {
        return goodDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_test..i_good.good_desc
     *
     * @param goodDesc the value for i_test..i_good.good_desc
     *
     * @mbggenerated
     */
    public void setGoodDesc(String goodDesc) {
        this.goodDesc = goodDesc == null ? null : goodDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_test..i_good.create_date
     *
     * @return the value of i_test..i_good.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_test..i_good.create_date
     *
     * @param createDate the value for i_test..i_good.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_test..i_good.created_time
     *
     * @return the value of i_test..i_good.created_time
     *
     * @mbggenerated
     */
    public Timestamp getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_test..i_good.created_time
     *
     * @param createdTime the value for i_test..i_good.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Timestamp createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_test..i_good.updated_time
     *
     * @return the value of i_test..i_good.updated_time
     *
     * @mbggenerated
     */
    public Timestamp getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_test..i_good.updated_time
     *
     * @param updatedTime the value for i_test..i_good.updated_time
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Timestamp updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_test..i_good
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", goodName=").append(goodName);
        sb.append(", goodLeft=").append(goodLeft);
        sb.append(", goodDesc=").append(goodDesc);
        sb.append(", createDate=").append(createDate);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}