package com.example.demo.dao;

import com.example.demo.model.IGood;

import java.util.List;

public interface IGoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_test..i_good
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_test..i_good
     *
     * @mbggenerated
     */
    int insert(IGood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_test..i_good
     *
     * @mbggenerated
     */
    int insertSelective(IGood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_test..i_good
     *
     * @mbggenerated
     */
    IGood selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_test..i_good
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IGood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_test..i_good
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IGood record);

    List<IGood> selectAllGoods();

    List<IGood> selectGoodsByCondition(IGood good);
}